apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp_deployment
  label:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp_pod
      label:
        app: webapp
    spec:
      containers:
        - name: webapp_con  
          image: charanreddy12/webapp:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: webapp_service
  label:
    app: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
