name: implementing cicd pipeline

on: 
    workflow_dispatch:

jobs:
    compile:
        runs-on: self-hosted
        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: setup JDK 21.0.6
          uses: actions/setup-java@v4
          with:
            java-version: '21.0.6'
            distribution: 'temurin'
            cache: 'maven'
        - name: compile code
          run: mvn compile

        - name: testing the code
          run: mvn test

    sonar_code_scan:
        needs: compile
        runs-on: self-hosted
        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: setup JDK 21.0.6
          uses: actions/setup-java@v4
          with:
            java-version: '21.0.6'
            distribution: 'temurin'
            cache: 'maven'

        - name: sonar scan
          uses: SonarSource/sonarqube-scan-action@v5.1.0
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}